const data = {
  collections: [
    {
      img: "https://m.media-amazon.com/images/I/71an9eiBxpL._AC_SL1500_.jpg",
      section: "laptop",
      title: "Laptops collection",
    },
    {
      title: "Gaming Collection",
      section: "gaming",
      img: "https://m.media-amazon.com/images/I/41ARx5IO3bL._AC_UL480_QL65_.jpg",
    },
    {
      title: "Computer Accessories Collection",
      section: "computer%20accessories",
      img: "https://preview.colorlib.com/theme/electro/img/shop03.png",
    },
    {
      title: "Sunglasses collection",
      section: "sunglasses",
      img: "https://m.media-amazon.com/images/I/51OPcdnMQTL._AC_SX679_.jpg",
    },
    {
      title: "Kitchen collection",
      section: "kitchen",
      img: "https://images-na.ssl-images-amazon.com/images/I/71xDpa7FggL.__AC_SX300_SY300_QL70_ML2_.jpg",
    },
    {
      title: "Clothes collection",
      section: "clothes",
      img: "https://m.media-amazon.com/images/I/31fctdEYGGS._AC_UL480_FMwebp_QL65_.jpg",
    },
  ],
  products: [
    {
      id: 0,
      title: "Title Goes Here",
      imgs: [
        "https://m.media-amazon.com/images/I/71an9eiBxpL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71iGJlR9S5L._AC_SX425_.jpg",
      ],
      brand: "Apple",
      page: ["laptop"],
      rating: {
        rate: 4.7,
        count: 500,
      },
      isNew: false,
      description: [
        "Computer CPU Manufacturer : Apple",
        " Model Number : MYD82",
        "Processor Speed (GHz) : 3.2 GHz",
        " Hardware Platform : MAC OS",
        " Processor Type : Apple M1",
        " USB : USB C",
        "Brand : Apple",
        "Laptop Family : Laptop",
        "Graphics Card Capacity : Shared - Built in",
        "Memory Card Reader : No",
        "Touch screen : No",
        "Keyboard Languages : English",
        "Usage : Multi",
        "Screen Size Range : 13 - 13.9 inches",
        "Memory Technology : Unified RAM",
        "Display Size (Inch) : 13.3 inches",
        " Number of Processor Core : Octa Core",
        "Optical Drive Type : Without Optical Drive",
        " RAM Type : Unified RAM",
        "RAM Size : 8 GB",
        "Operating System Type : Mac OS",
      ],
      price: 23750,
      discount: false,
      "discount-amount": null,
      category: "laptop",
      testimonial: [
        {
          name: "FarrahElhusseiny",
          rate: 3,
          comment:
            "8GB es bastante ajustado tomando en cuenta que no vas a poder actualizarlo",
        },
        {
          name: "user",
          rate: 3,
          comment: "Descontento con empresa de transporte.",
        },
        {
          name: "Eleni",
          rate: 5,
          comment: "Perfecto touch bar",
        },
        {
          name: "Ahmed ",
          rate: 4.8,
          comment: "good",
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rating: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "That's sound cool",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "hello from test",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "hello from test",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "   ",
          rate: 4.5,
        },
        {
          name: "Abdo",
          comment: "                     ",
          rate: 4,
        },
        {
          name: "Abdo",
          comment: "when you write tehe comment it's updated in the data-base",
          rate: 2.5,
        },
      ],
    },
    {
      id: 1,
      title:
        "Apple iPhone 11 with FaceTime - 64GB, 4GB RAM, 4G LTE, Yellow, Single SIM & E-SIM",
      page: ["mobile"],
      imgs: [
        "https://images-na.ssl-images-amazon.com/images/I/71Z8C1zRgAL.__AC_SX300_SY300_QL70_ML2_.jpg",
        "https://m.media-amazon.com/images/I/71eDZ1oipzL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/715mr2e667L._AC_SX522_.jpg",
        "https://m.media-amazon.com/images/I/813VPIzw++L._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/71SmWQ1KE3L._AC_SX425_.jpg",
      ],
      brand: "Apple",
      description: [
        "ROM: 4GB",
        "4G LTE",
        "Splash, Water and Dust Resistant",
        "A13 Bionic chip",
        "TrueDepth camera 12MP camera",
        "Apple Pay",
      ],
      price: 12055,
      discount: false,
      "discount-amount": null,
      rating: {
        rate: 4.1,
        count: 430,
      },
      isNew: true,
      category: "mobile",
      testimonial: [
        {
          name: "Khaled",
          rate: 4.8,
          comment: "EXCELLENT AS USUAL",
        },
      ],
    },
    {
      id: 2,
      title: "Pierced Owl Rose Gold Plated Stainless Steel Double",
      price: 10.99,
      brand: "other",
      description: [
        "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
      ],
      page: ["accessories"],
      category: "jewelery",
      imgs: [
        "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
      ],
      rating: {
        rate: 1.9,
        count: 100,
      },
      isNew: false,
      discount: false,
      "discount-amount": null,
      testimonial: [
        {
          name: "Abdo",
          comment: "mm",
          rate: 3,
        },
        {
          name: "Abdo",
          comment: "this my opinion",
          rate: 4.5,
        },
      ],
    },
    {
      id: 3,
      price: 95,
      title: "Title Goes Here",
      description: [
        "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
      ],
      category: "womens%20clothes",
      page: ["clothes"],
      brand: "other",
      imgs: ["https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg"],
      rating: {
        rate: 4.7,
        count: 130,
      },
      isNew: false,
      discount: true,
      "discount-amount": 5,
    },
    {
      id: 4,
      title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
      price: 109,
      brand: "other",
      description: [],
      isNew: false,
      category: "electronics",
      page: ["gaming", "computer%20accessories"],
      imgs: ["https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg"],
      rating: {
        rate: 2.9,
        count: 470,
      },
      discount: true,
      "discount-amount": 25,
    },
    {
      id: 5,
      price: 999,
      title: "Title Goes Here",
      isNew: true,
      brand: "other",
      page: ["gaming", "electronics"],
      description: [],
      category: "electronics",
      imgs: ["https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg"],
      rating: {
        rate: 2.2,
        count: 140,
      },
      discount: true,
      "discount-amount": 85,
      testimonial: [
        {
          name: "Abdo",
          comment: "good",
          rate: 4,
        },
      ],
    },
    {
      id: 6,
      title: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
      price: 64,
      description: [
        "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
      ],
      isNew: true,
      category: "electronics",
      page: ["electronics"],
      brand: "other",
      imgs: ["https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg"],
      rating: {
        rate: 3.3,
        count: 203,
      },
      discount: false,
      "discount-amount": null,
    },
    {
      id: 7,
      title:
        "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
      price: 114,
      brand: "other",
      page: ["gaming", "computer%20accessories"],
      description: [
        "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
      ],
      category: "electronics",
      imgs: ["https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg"],
      rating: {
        rate: 4.8,
        count: 400,
      },
      isNew: false,
      discount: false,
      "discount-amount": null,
      testimonial: [
        {
          name: "Abdo",
          comment: "comments here",
          rate: 3.5,
        },
      ],
    },
    {
      id: 8,
      title: "Mens Casual Premium Slim Fit T-Shirts ",
      price: 22.3,
      isNew: false,
      description: [],
      category: "mens%20clothes",
      page: ["clothes"],
      brand: "other",
      imgs: [
        "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
      ],
      rating: {
        rate: 4.1,
        count: 259,
      },
      discount: false,
      "discount-amount": null,
    },
    {
      id: 9,
      title: "Mens Casual Slim Fit",
      price: 15.99,
      description: [
        "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
      ],
      isNew: true,
      brand: "other",
      category: "mens%20clothes",
      page: ["clothes"],
      imgs: ["https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg"],
      rating: {
        rate: 2.1,
        count: 430,
      },
      discount: true,
      "discount-amount": 5,
    },
    {
      id: 10,
      title:
        "Delonghi Espresso Machine - Silver Ec685.M ( International Warranty )",
      imgs: [
        "https://images-na.ssl-images-amazon.com/images/I/71xDpa7FggL.__AC_SX300_SY300_QL70_ML2_.jpg",
        "https://m.media-amazon.com/images/I/71pk8IF48NL._AC_SY606_.jpg",
        "https://m.media-amazon.com/images/I/81X6fTAQwIL._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/81y8ddKPH7L._AC_SY606_.jpg",
      ],
      brand: "other",
      page: ["kitchen", "electronics"],
      rating: {
        rate: 3.9,
        count: 138,
      },
      isNew: true,
      description: [
        "Smart Design",
        "Exemplary Elegance",
        "According to your Taste",
      ],
      features: [
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/sota/4399f62b-1fa2-41e6-a09c-b4bb05c0ee2c.__CR0,0,1500,1500_PT0_SX300_V1___.jpg",
          description:
            "Get yourself a cup of freshly brewed coffee with the Black & Decker Coffee Machine to drive all your boredom away! It is designed with an auto-shutoff feature for efficiency and safety. A nylon filter for durability and one-button operation for ease of use make this classy-looking Black & Decker 350W Coffee Machine worth a buy.",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/sota/c1adb2bd-7620-4048-aaeb-fe6e6aebfce2.__CR0,0,1500,1500_PT0_SX300_V1___.jpg",
          title: "Stylish Appearance",
          description:
            "The Black & Decker Coffee Maker sports a stylish design that will surely complement your countertop. Its compact profile perfectly blends with your home or office settings while saving on space.",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/sota/4e7537b5-171f-40fa-b030-b5842d70c8bf.__CR0,0,1500,1500_PT0_SX300_V1___.jpg",
          title: "Easy-to-use Design",
        },
      ],
      price: 3848,
      discount: false,
      "discount-amount": null,
      category: "coffee%20machine",
      testimonial: [
        {
          name: "reham",
          rate: 3,
          comment: "Good",
        },
        {
          name: "user",
          rate: 4,
          comment: "Fast delivry",
        },
      ],
    },
    {
      id: 11,
      title: "Maxell Magic Spray Kitchen Cleaner with Oven Cleaner, 2 Pieces",
      imgs: [
        "https://images-na.ssl-images-amazon.com/images/I/71dqxCguxbL.__AC_SX300_SY300_QL70_ML2_.jpg",
        "https://m.media-amazon.com/images/I/71MnkUPY92L._AC_SY879_.jpg",
        "https://m.media-amazon.com/images/I/81U4Ig2K09L._AC_SY450_.jpg",
        "https://m.media-amazon.com/images/I/71BKJbCxz3L._AC_SY879_.jpg",
        "https://m.media-amazon.com/images/I/810ByXQ34oL._AC_SY450_.jpg",
      ],
      isNew: false,
      brand: "Philips",
      page: ["kitchen"],
      rating: {
        rate: 4,
        count: 128,
      },
      description: [
        "Anti Bacteria Kitchen Cleaner",
        "Brand: Maxell",
        "Size: 700 ml",
        "Also you will get an Ovens cleaner with it.",
        "Brand: Maxell",
        "Size: 500 ml",
        "Anti Bacteria",
      ],
      features: null,
      price: 59,
      discount: false,
      "discount-amount": null,
      category: "other",
      testimonial: [],
    },
    {
      id: 12,
      title:
        "PHILIPS Essential Air Fryer, Analogue, Black, 50 hz, HD9200/91 ( International warranty )",
      imgs: [
        "https://m.media-amazon.com/images/I/816v0jKNweL._AC_UL480_FMwebp_QL65_.jpg",
        "https://m.media-amazon.com/images/I/71X0wt1UdLL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/61wYKU0UYyL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/51+RAx0LhiL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/61T8gY+E08L._AC_SX425_.jpg",
      ],
      brand: "Philips",
      isNew: true,
      rating: {
        rate: 3.9,
        count: 138,
      },
      description: [
        "As crispy as deep fried with 90% less fatFry with little or no added oilTwin Turbo Star technology removes fat from foodsDigital display with 5 preset cooking programsQuick Clean basket with non-stick mesh cleans up in 90 secsDishwasher safe for all removable partsFry, bake, grill and roast your favorite foods at homeOur most powerful Airfryer for faster cooking resultsRecipe booklet with more than 30 delicious dishesXXL family size fits a whole chicken or 1.4 kg of fries",
      ],
      features: [
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/7bb51e18-3171-4745-8593-bda016508300.__CR0,952,3312,1024_PT0_SX970_V1___.jpg",
          title: "Maximum Taste, minimum fat",
          description:
            "Crispy taste, reduces fat others leave behind Compared on fat content of chicken versus a deep fat fryer and wok frying",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/1f84efef-8c5d-4c37-8e7a-d463f220b252.__CR0,0,300,300_PT0_SX300_V1___.jpg",
          title: "Maximum taste, minimum fat",
          description:
            "The Philips Airfryer uses hot air to fry your favourite food with little or no added oil. New Fat Removal technology is designed to extract and capture fat from the food, making this the healthiest way to fry for you and your family.",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/2db0f510-3c8e-4c86-8ce8-3fe2ab9bdacc.__CR0,0,300,300_PT0_SX300_V1___.jpg",
          title: " XXL family size fits a whole chicken or 1.4 kg of fries ",
          description:
            " Yes, you can cook family-size meals in the new Airfryer XXL. It's full-size capacity makes cooking a large, delicious meal easy. You can cook a whole chicken or even up to 1.4 kg of fries to satisfy hungry family or friends. Serve up to six portions with the large 7.3L capacity basket. ",
        },
      ],
      price: 5188,
      discount: true,
      "discount-amount": 1318,
      page: ["kitchen", "electronics"],
      category: "fryer",
      testimonial: [
        {
          name: "Ahmed",
          rate: 4.5,
          comment: "Good",
        },
        {
          name: "Nader",
          rate: 4,
          comment: "Fast delivry",
        },
      ],
    },
    {
      id: 13,
      title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
      price: 109.95,
      isNew: true,
      description: [
        "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
      ],
      category: "mens%20clothes",
      page: ["clothes"],
      imgs: ["https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"],
      rating: {
        rate: 3.9,
        count: 120,
      },
      discount: false,
      "discount-amount": null,
    },
    {
      id: 14,
      title:
        "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
      price: 695,
      description: [
        "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
      ],
      isNew: false,
      category: "jewelery",
      page: ["accessories"],
      imgs: [
        "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
      ],
      rating: {
        rate: 4.6,
        count: 400,
      },
      discount: true,
      "discount-amount": 55,
    },
    {
      id: 15,
      title:
        "Philips 1.2 KGS Deep Fryer - HD9270/90 ( International warranty )",
      imgs: [
        "https://m.media-amazon.com/images/I/51I8gXi1tCS._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/8158RHVGxLS._AC_SL1500_.jpg",
      ],
      isNew: false,
      brand: "Philips",
      page: ["kitchen", "electronics"],
      rating: {
        rate: 3.9,
        count: 138,
      },
      description: [],
      features: [
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/6dfc2671-8db5-4369-ba60-c74cbc92378c.__CR0,0,1767,1767_PT0_SX300_V1___.jpg",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/ba4a45cd-0c8e-44a0-8447-df3fe76a4139.__CR75,0,450,450_PT0_SX300_V1___.jpg",
          title: "Fry with up to 90% less fat*",
          description:
            "The Philips Essential Airfryer uses hot air to cook your favorite foods to crispy perfection, with up to 90% less fat Compared to fresh fries prepared in a Philips conventional fryer",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/a1d6dd96-b1f4-476f-aae1-97adce08fdcb.__CR0,0,1536,1536_PT0_SX300_V1___.jpg",
          title: "Tasty Airfryer recipes for healthy living",
          description:
            "Discover hundreds of mouthwatering Airfryer recipes that are tasty, healthy, and fast to make. The recipes in the NutriU app are curated by nutritional experts for everyday cooking.",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/f14706cc-9dba-4352-a62c-da670e081db1.__CR0,0,1040,1040_PT0_SX300_V1___.jpg",
          title: "Keep warm function",
        },
        {
          img: "https://m.media-amazon.com/images/S/aplus-media/vc/f14706cc-9dba-4352-a62c-da670e081db1.__CR0,0,1040,1040_PT0_SX300_V1___.jpg",
          title: "The No.1 low-fat fryer",
          description:
            "Philips is the global leader in the low-fat fryer brand Source: Euromonitor International Ltd. Low fat fryers category definition; retail volume sales in units, 2020 data",
        },
      ],
      price: 3151,
      discount: true,
      "discount-amount": 1350,
      category: "fryer",
      testimonial: [
        {
          name: "Amal",
          rate: 3,
          comment: "good",
        },
        {
          name: "user",
          rate: 3,
          comment: "best product",
        },
      ],
    },
    {
      id: 16,
      title: "Apple AirPods with Charging Case, MV7N2ZP/A - White",
      imgs: [
        "https://m.media-amazon.com/images/I/21-uFkJzl4L._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/31nbaxRZ9xL._AC_.jpg",
        "https://m.media-amazon.com/images/I/21VlDuPfDYL._AC_.jpg",
      ],
      isNew: false,
      brand: "Apple",
      page: ["gaming", "computer%20accessories", "Abdelrahman"],
      rating: {
        rate: 5,
        count: 250,
      },
      description: [
        "Batteries  :  1 Lithium Polymer batteries required. (included)",
        "Product Dimensions:  10.1 x 10.1 x 3.4 cm; 40 Grams",
        "Date First Available:  11 February 2021",
        "Manufacturer:  Apple Computer",
        "ASIN:  B07NWBVQWK",
        "Item model number:  MV7N2ZP/A",
        "Best Sellers Rank: #5,420 in Electronics (See Top 100 in Electronics)",
        "#120 in In-Ear Headphones",
      ],
      features: null,
      price: 2990,
      discount: false,
      "discount-amount": null,
      category: "headphone",
      testimonial: [],
    },
    {
      id: 17,
      title:
        "Digital Instant Read Candy Thermometer, Kitchen Cooking Food Meat Thermometer with Calibration, Magnet, Foldable Probe, Large Screen, BBQ Grill Smoker Thermometer for Grilling, Oven.",
      imgs: [
        "https://m.media-amazon.com/images/I/71b85YDCB9L._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/71FFAoIkThL._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/71I+xZZ+UrL._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/71I09IGtVtS._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/41CZj-rrmmL._AC_SX425_.jpg",
      ],
      brand: "other",
      page: ["kitchen"],
      rating: {
        rate: 4,
        count: 68,
      },
      isNew: false,
      description: [
        "★【INSTANT READ & ACCURATE】Instant Read Meat Thermometer equip with 4-5 Seconds reading out speed brings you accurate and healthy temp; accurate to ±0.5℉, prevent you from the Salmonella in under cooked meat.",
      ],
      features: null,
      price: 59,
      discount: false,
      "discount-amount": null,
      category: "other",
      testimonial: [],
    },
    {
      id: 18,
      title: "Red Gaming Chair Racer",
      imgs: [
        "https://m.media-amazon.com/images/I/41d5gFbvQGL._AC_.jpg",
        "https://m.media-amazon.com/images/I/61GN02FH8HL._AC_SY741_.jpg",
        "https://m.media-amazon.com/images/I/51nPG0GUIeL._AC_SY879_.jpg",
      ],
      isNew: false,
      brand: "other",
      page: ["gaming", "computer%20accessories"],
      rating: {
        rate: 4.5,
        count: 240,
      },
      description: [
        "Type : Office Chairs",
        "Brand : Other",
        "Material : Faux Leather",
        "Height : 120 centimeters",
        "Depth : 50 centimeters",
      ],
      features: [],
      price: 2571,
      discount: false,
      "discount-amount": null,
      category: "gaming",
      testimonial: [
        {
          name: "Ibrahim",
          rate: 5,
          comment: "very comfortable",
        },
        {
          name: "Abdo",
          comment: "hello world",
          rate: 0.5,
        },
      ],
    },
    {
      id: 19,
      title:
        "Alpine Swiss Mens Polarized Sunglasses Lightweight 100% UV 400 Protection, ASPSG-077BRN, James Square",
      imgs: [
        "https://m.media-amazon.com/images/I/516S7KdToGL._AC_SX522_.jpg",
        "https://m.media-amazon.com/images/I/51uhs9VPCBL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/41N62Z8Li3L._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/4106MdpXBkL._AC_SX679_.jpg",
      ],
      isNew: true,
      brand: "other",
      page: ["sunglasses", "accessories"],
      rating: {
        rate: 4.5,
        count: 2,
      },
      description: [
        "American Brand: all products are produced in India or China with American quality control and assurance.",
        "STYLISH FRAMES - The Alpine Swiss James square sunglasses are a modern take on the classic square frame look. These versatile and stylish angular frames look great on many face shapes and elevate any outfit. Round, oval, and heart shaped faces emphasize the classic and fashion forward details of these frames making them a timeless accessory.",
        "LIGHTWEIGHT MATERIALS - Choose from multiple frame colors that are built with durable yet lightweight TRP 90 plastic. Gunmetal tone legs, metal spring hinges, and ergonomically designed frames comfortably accommodate your face and stay securely in place on your nose and around your ears. Our signature Alpine Swiss logo is elegantly engraved in the top corner of the left lens.",
      ],
      features: [],
      price: 879,
      discount: false,
      "discount-amount": null,
      category: "sunglasses",
      testimonial: [
        {
          name: "Mohammed",
          rate: 5,
          comment: "It's Original ",
        },
      ],
    },
    {
      id: 20,
      title: "Royal Son UV Protected Aviator Unisex Sunglasses",
      imgs: [
        "https://m.media-amazon.com/images/I/61vDYF4JaxL._AC_SX522_.jpg",
        "https://m.media-amazon.com/images/I/41cBDEirIFL._AC_.jpg",
        "https://m.media-amazon.com/images/I/71IsJT1FEsL._AC_SX522_.jpg",
        "https://m.media-amazon.com/images/I/71vwwYdu2RL._AC_SX522_.jpg",
      ],
      brand: "other",
      page: ["sunglasses", "accessories"],
      rating: {
        rate: 4.5,
        count: 2,
      },
      description: [
        "Black Lens With Golden Frame ( There may be slightly difference with dp and item in hand product )",
        "Acrylic Lens With Metal Frame",
        "Sunglasses with Case",
      ],
      isNew: false,
      features: [],
      price: 118,
      discount: true,
      "discount-amount": 122,
      category: "sunglasses",
      testimonial: [
        {
          name: "Ismaeal",
          rate: 4.5,
          comment: "It looks cool!",
        },
      ],
    },
    {
      id: 21,
      title:
        "Unique Steampunk Lens Retro Metal Frame Sunglasses Women Men Eyewear Sun Glasses Mens Sunglasses Brand Tinize Outdoor Protection Vintage Sport Sunglasses",
      imgs: [
        "https://m.media-amazon.com/images/I/41Bf066cDwL._AC_SX522_.jpg",
        "https://m.media-amazon.com/images/I/51bKf25AfiL._AC_SX679_.jpg",
        "https://m.media-amazon.com/images/I/51tsg+xWc5L._AC_SX425_.jpg",
        "https://m.media-amazon.com/images/I/51dtmNLCDuL._AC_SX679_.jpg",
      ],
      isNew: true,
      brand: "other",
      page: ["sunglasses", "accessories"],
      rating: {
        rate: 3.5,
        count: 18,
      },
      description: [
        "Type : Sunglasses",
        "Targeted Group : Unisex",
        "Frame Shape : Round",
        "Frame Material : Metal",
        "Polarized Lenses : Yes",
        "Lens Color Family : Multi Color",
        "Brand : Other",
      ],
      features: [],
      price: 126,
      discount: false,
      "discount-amount": null,
      category: "sunglasses",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "good but not like i want",
        },
      ],
    },
    {
      id: 22,
      title:
        "Round Metal Sunglasses Steampunk Men Women Fashion Glasses Brand Designer Retro Vintage Sunglasses UV400",
      imgs: [
        "https://m.media-amazon.com/images/I/51c4D9Jo3ZL._AC_SY500_.jpg",
        "https://m.media-amazon.com/images/I/31B1a8RD0ML._AC_.jpg",
        "https://m.media-amazon.com/images/I/51Ea-GmMH8L._AC_SY500_.jpg",
      ],
      isNew: true,
      brand: "other",
      page: ["sunglasses", "accessories"],
      rating: {
        rate: 3.5,
        count: 18,
      },
      description: [
        "Type : Sunglasses",
        "Targeted Group : Unisex",
        "Frame Shape : Round",
        "Frame Material : Metal",
        "Polarized Lenses : Yes",
        "Lens Color Family : Black",
        "Brand : Other",
      ],
      features: [],
      price: 240,
      discount: false,
      "discount-amount": null,
      category: "sunglasses",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "good but not like i want",
        },
      ],
    },
    {
      id: 23,
      title: "Product title goes here",
      imgs: [
        "https://preview.colorlib.com/theme/electro/img/xproduct01.png.pagespeed.ic.flJc5JT8yl.webp",
      ],
      isNew: true,
      brand: "other",
      page: ["laptop"],
      rating: {
        rate: 4,
        count: 18,
      },
      description: ["Description Goes Here"],
      features: [],
      price: 540,
      discount: false,
      "discount-amount": null,
      category: "laptop",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "good but not like i want",
        },
      ],
    },
    {
      id: 24,
      imgs: [
        "https://preview.colorlib.com/theme/electro/img/xproduct03.png.pagespeed.ic.cQrB7wvQ5E.webp",
      ],
      title: "Product title goes here",
      isNew: true,
      brand: "other",
      page: ["laptop"],
      rating: {
        rate: 4,
        count: 25,
      },
      description: ["Description Goes Here"],
      features: [],
      price: 20180,
      discount: false,
      "discount-amount": null,
      category: "laptop",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "Operating system super fast",
        },
      ],
    },
    {
      id: 25,
      imgs: [
        "https://preview.colorlib.com/theme/electro/img/xproduct07.png.pagespeed.ic.96craXAXfp.webp",
      ],
      title: "Product title goes here",
      isNew: false,
      brand: "Samsung",
      page: ["mobile"],
      rating: {
        rate: 4,
        count: 25,
      },
      description: ["Description Goes Here"],
      features: [],
      price: 20180,
      discount: false,
      "discount-amount": null,
      category: "mobile",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "Operating system super fast",
        },
      ],
    },
    {
      id: 26,
      imgs: [
        "https://preview.colorlib.com/theme/electro/img/xproduct08.png.pagespeed.ic.VCq0LEalYT.webp",
      ],
      title: "Product title goes here",
      isNew: false,
      brand: "Asus",
      page: ["laptop"],
      rating: {
        rate: 4,
        count: 25,
      },
      description: ["Description Goes Here"],
      features: [],
      price: 20180,
      discount: false,
      "discount-amount": null,
      category: "laptop",
      testimonial: [
        {
          name: "Reda",
          rate: 4.5,
          comment: "It looks cool!",
        },
        {
          name: "Ahmed",
          rate: 4,
          comment: "Operating system super fast",
        },
      ],
    },
  ],
};

export const { collections, products } = data;
